

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
buildscript {
    repositories {
        gradlePluginPortal()
        maven("https://papermc.io/repo/repository/maven-public/")
    }
    dependencies {
        classpath("io.papermc.paperweight.userdev:io.papermc.paperweight.userdev.gradle.plugin:1.7.1")
    }
}


rootProject.name = "pathetic-main"
include(":pathetic-mapping")
include(":pathetic-example")
include(":pathetic-nms")
include(":pathetic-model")
include(":v1_20_R4")
include(":pathetic-api")
project(":v1_20_R4").projectDir = file("pathetic-nms/v1_20_R4")
