/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":pathetic-api"))
    api(project(":pathetic-nms"))
    api(libs.org.bstats.bstats.bukkit)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.org.projectlombok.lombok)
    compileOnly(libs.org.apache.logging.log4j.log4j.core)
    compileOnly(libs.com.google.guava.guava)
    annotationProcessor(libs.org.projectlombok.lombok)

}

description = "pathetic-model"
