/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":pathetic-model"))
    annotationProcessor(libs.org.projectlombok.lombok)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "pathetic-mapping"
