/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.papermc.paperweight.userdev")
}

repositories {
    maven("https://papermc.io/repo/repository/maven-public/")

}


dependencies {
    paperweight.paperDevBundle("1.20.6-R0.1-SNAPSHOT")

    compileOnly(project(":pathetic-api"))
}

description = "v1_20_R4"
