/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}


dependencies {
    api(project(":v1_20_R4"))
    compileOnly(project(":pathetic-api"))
}


description = "pathetic-nms"
